font_family      Iosevka
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 19

enable_audio_bell no

hide_window_decorations titlebar-only
window_margin_width 4
cursor_blink_interval 0
macos_quit_when_last_window_closed no
macos_colorspace default
repaint_delay 8
input_delay 1
resize_draw_strategy blank
remember_window_size no
resize_debounce_time 0.001
allow_remote_control true

tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol 
tab_title_max_length 25
tab_title_template "{fmt.fg.red}{bell_symbol}{fmt.fg.tab} {index}: {tab.active_oldest_exe} {activity_symbol}"

cursor_shape beam

# macos commands
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5

map cmd+t launch --type=tab --cwd=current
map cmd+n launch --type=os-window --cwd=current
map ctrl+s launch --location=vsplit
map ctrl+shift+s launch --location=hsplit
map ctrl+j neighboring_window left
map ctrl+k neighboring_window right
map ctrl+shift+j neighboring_window up
map ctrl+shift+k neighboring_window down
map ctrl+q close_window
map ctrl+; next_layout

symbol_map U+F0001-U+F1af0 Hack Nerd Font
symbol_map U+F8FF,U+100000-U+1018C7 SF Pro

# linux commands
map ctrl+1 goto_tab 1
map ctrl+2 goto_tab 2
map ctrl+3 goto_tab 3
map ctrl+4 goto_tab 4
map ctrl+5 goto_tab 5
map ctrl+t launch --type=tab --cwd=current
map ctrl+n launch --type=os-window --cwd=current

# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# The basic colors
foreground              #CDD6F4
background              #1E1E2E
selection_foreground    #1E1E2E
selection_background    #F5E0DC

# Cursor colors
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #F5E0DC

# Kitty window border colors
active_border_color     #B4BEFE
inactive_border_color   #6C7086
bell_border_color       #F9E2AF

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111B
active_tab_background   #A6E3A1
inactive_tab_foreground #CDD6F4
inactive_tab_background #3C3E4F
tab_bar_background      #11111B

# Colors for marks (marked text in the terminal)
mark1_foreground #1E1E2E
mark1_background #B4BEFE
mark2_foreground #1E1E2E
mark2_background #CBA6F7
mark3_foreground #1E1E2E
mark3_background #74C7EC

# The 16 terminal colors

# black
color0 #45475A
color8 #585B70

# red
color1 #F38BA8
color9 #F38BA8

# green
color2  #A6E3A1
color10 #A6E3A1

# yellow
color3  #F9E2AF
color11 #F9E2AF

# blue
color4  #89B4FA
color12 #89B4FA

# magenta
color5  #F5C2E7
color13 #F5C2E7

# cyan
color6  #94E2D5
color14 #94E2D5

# white
color7  #BAC2DE
color15 #A6ADC8



