scan_timeout = 500
add_newline = false

[character]
success_symbol = "[>](bold #9ece6a)"
error_symbol = "[x](bold #f7768e)"
vicmd_symbol = "[V](bold #7aa2f7)"

[directory]
style = "bold #7aa2f7"
read_only = " ro"
truncation_length = 3

[git_branch]
style = "bold #bb9af7"

[git_status]
disabled = false
style = "#e0af68"

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '
added_style = "#9ece6a"
deleted_style = "#f7768e"

[battery]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

[package]
disabled = true

[nix_shell]
symbol = " "
style = "#7dcfff"
