scan_timeout = 500
add_newline = false

[character]
success_symbol = "[>](bold #50fa7b)"
error_symbol = "[x](bold #ff5555)"
vicmd_symbol = "[V](bold #6272a4)"

[directory]
style = "bold #6272a4"
read_only = " ro"
truncation_length = 3

[git_branch]
style = "bold #bd93f9"

[git_status]
disabled = false
style = "#f1fa8c"

[git_commit]
commit_hash_length = 7
tag_disabled = false
only_detached = false

[git_metrics]
disabled = false
format = '([+$added]($added_style)) ([-$deleted]($deleted_style)) '
added_style = "#50fa7b"
deleted_style = "#ff5555"

[battery]
disabled = true

[python]
disabled = true

[cmake]
disabled = true

[package]
disabled = true

[nix_shell]
symbol = " "
style = "#8be9fd"
