;; Theme: dracula
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg = #282a36
bg1 = #44475a
bg2 = #44475a
fg = #f8f8f2

;; for 50% transparent
trans1 = #80000000
;; 100% transparent
trans2 = #00

;; colors
black = #282a36
black1 = #282a36
white = #f8f8f2
red = #ff5555
green = #50fa7b
yellow = #f1fa8c
blue = #6272a4
purple = #bd93f9
cyan = #8be9fd
orange = #f1fa8c
magenta = #bd93f9
gray = #f8f8f2

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
