;; Theme: catppuccin
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg = #1E1E2E
bg1 = #313244
bg2 = #313244
fg = #CDD6F4

;; for 50% transparent
trans1 = #80000000
;; 100% transparent
trans2 = #00

;; colors
black = #1E1E2E
black1 = #1E1E2E
white = #CDD6F4
red = #F38BA8
green = #A6E3A1
yellow = #F9E2AF
blue = #89B4FA
purple = #CBA6F7
purpledark = #CBA6F7
cyan = #94E2D5
teal = #94E2D5
ocean = #89B4FA
orange = #F9E2AF
magenta = #CBA6F7
gray = #CDD6F4
bluedark = #313244
cream = #CDD6F4
indigo = #313244
pink = #CBA6F7
shade2 = #313244
shade3 = #313244
shade4 = #313244

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
