display-name = "Ben A."

################################ PERSONAL GMAIL ##############################################

[accounts.gmail]
email = "benny.ouattara@gmail.com"
default = true

[accounts.gmail.backend]
type = "imap"
host = "imap.gmail.com"
port = 993
login = "benny.ouattara@gmail.com"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/gmail"

[accounts.gmail.message.send]
type = "smtp"
host = "smtp.gmail.com"
port = 587
login = "benny.ouattara@gmail.com"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/gmail"

[accounts.gmail.folder.alias]
inbox = "INBOX"
sent = "[Gmail]/Sent Mail"
all = "[Gmail]/All Mail"

################################# PROTONMAIL ##############################################

[accounts.protonmail]
email = "ben.abubakar@proton.me"

[accounts.protonmail.backend]
type = "imap"
host = "127.0.0.1"
port = 1143
login = "ben.abubakar@proton.me"
encryption.type = "none"
auth.type = "password"
auth.cmd = "pass Email/proton"

[accounts.protonmail.message.send]
type = "smtp"
host = "127.0.0.1"
port = 1025
login = "ben.abubakar@proton.me"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/proton"

[accounts.protonmail.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"
spam = "Spam"

################################# JFUND ##############################################

[accounts.jfund]
email = "jazafund@proton.me"

[accounts.jfund.backend]
type = "imap"
host = "127.0.0.1"
port = 1143
login = "jazafund@proton.me"
encryption.type = "none"
auth.type = "password"
auth.cmd = "pass Email/jfund"

[accounts.jfund.message.send]
type = "smtp"
host = "127.0.0.1"
port = 1025
login = "jazafund@proton.me"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jfund"

[accounts.jfund.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"
spam = "Spam"

################################ JC SUPPORT ##############################################

[accounts.jcash-support]
email = "support@jaza.cash"

[accounts.jcash-support.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "support@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-support.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "support@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-support.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC OPS ##############################################

[accounts.jcash-ops]
email = "ops@jaza.cash"

[accounts.jcash-ops.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "ops@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-ops.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "ops@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-ops.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC COMPLIANCE ##############################################

[accounts.jcash-compliance]
email = "compliance@jaza.cash"

[accounts.jcash-compliance.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "compliance@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-compliance.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "compliance@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-compliance.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC INFO ##############################################

[accounts.jcash-info]
email = "info@jaza.cash"

[accounts.jcash-info.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "info@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-info.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "info@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-info.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC FRAUD ##############################################

[accounts.jcash-fraud]
email = "fraud@jaza.cash"

[accounts.jcash-fraud.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "fraud@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-fraud.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "fraud@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-fraud.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC HR ##############################################

[accounts.jcash-hr]
email = "hr@jaza.cash"

[accounts.jcash-hr.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "hr@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-hr.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "hr@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-hr.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC SALES ##############################################

[accounts.jcash-sales]
email = "sales@jaza.cash"

[accounts.jcash-sales.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "sales@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-sales.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "sales@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-sales.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JC SYSTEM ##############################################

[accounts.jcash-system]
email = "system@jaza.cash"

[accounts.jcash-system.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "system@jaza.cash"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-system.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "system@jaza.cash"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jcash"

[accounts.jcash-system.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JGROUP BEN ##############################################

[accounts.jgroup-ben]
email = "ben@jazagroup.com"

[accounts.jgroup-ben.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "ben@jazagroup.com"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jgroup"

[accounts.jgroup-ben.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "ben@jazagroup.com"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jgroup"

[accounts.jgroup-ben.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"

################################ JGROUP SYSTEM ##############################################

[accounts.jgroup-system]
email = "system@jazagroup.com"

[accounts.jgroup-system.backend]
type = "imap"
host = "heracles.mxrouting.net"
port = 993
login = "system@jazagroup.com"
encryption.type = "tls"
auth.type = "password"
auth.cmd = "pass Email/jgroup"

[accounts.jgroup-system.message.send]
type = "smtp"
host = "heracles.mxrouting.net"
port = 587
login = "system@jazagroup.com"
encryption.type = "start-tls"
auth.type = "password"
auth.cmd = "pass Email/jgroup"

[accounts.jgroup-system.folder.alias]
inbox = "INBOX"
sent = "Sent"
drafts = "Drafts"
trash = "Trash"
