(use-modules (gnu)
             ;; (nongnu packages linux)
             (gnu artwork) (gnu packages fonts) ;; This is an operating system configuration generated by the graphical installer.
             (gnu packages lisp)
             (gnu packages wm)
             (gnu packages fonts)
             (gnu packages shells)
             (gnu packages package-management)
             (gnu packages pulseaudio)
             (gnu system setuid)
             (gnu system shadow)
             (gnu services databases)
             (guix gexp)
             ;; (contactapp service)
             (gnu packages audio)
             (guix channels)
             (srfi srfi-1))
(use-service-modules
 cups
 desktop
 networking
 ssh
 sddm
 xorg
 syncthing
 monitoring
 pm
 virtualization
 cuirass
 mcron)

;; Allow members of the "video" group to change the screen brightness.
(define %backlight-udev-rule
  (udev-rule
   "90-backlight.rules"
   (string-append "ACTION==\"add\", SUBSYSTEM==\"backlight\", "
                  "RUN+=\"/run/current-system/profile/bin/chgrp video /sys/class/backlight/%k/brightness\""
                  "\n"
                  "ACTION==\"add\", SUBSYSTEM==\"backlight\", "
                  "RUN+=\"/run/current-system/profile/bin/chmod g+w /sys/class/backlight/%k/brightness\"")))

(define %xorg-libinput-config
  "Section \"InputClass\"
  Identifier \"Touchpads\"
  Driver \"libinput\"
  MatchDevicePath \"/dev/input/event*\"
  MatchIsTouchpad \"on\"

  Option \"Tapping\" \"on\"
  Option \"TappingDrag\" \"on\"
  Option \"DisableWhileTyping\" \"on\"
  Option \"MiddleEmulation\" \"on\"
  Option \"ScrollMethod\" \"twofinger\"
  Option \"NaturalScrolling\" \"true\"
EndSection
Section \"InputClass\"
  Identifier \"Keyboards\"
  Driver \"libinput\"
  MatchDevicePath \"/dev/input/event*\"
  MatchIsKeyboard \"on\"
EndSection
")

(define %beno-motd
  (plain-file "motd" "Hi Ben, welcome!\n\n"))

(define %beno-console-font
  (file-append font-tamzen "/share/kbd/consolefonts/Tamzen10x20.psf"))

(define %modified-desktop-services
  (modify-services %desktop-services
    (delete console-font-service-type)  ;; provide other console fonts below
    (delete gdm-service-type)
    (login-service-type config =>
                        (login-configuration (inherit config)
                                             (motd %beno-motd)))
    (guix-service-type config =>
                       (guix-configuration (inherit config)
                                           (substitute-urls
                                            (append (list "https://substitutes.nonguix.org")
                                                    %default-substitute-urls))
                                           (authorized-keys
                                            (append (list (local-file "./nonguix-key.pub")
                                                          (local-file "./cuirass-key.pub"))
                                                    %default-authorized-guix-keys))))
    (elogind-service-type config =>
                          (elogind-configuration (inherit config)
                                                 (handle-lid-switch-external-power 'suspend)))
    (udev-service-type config =>
                       (udev-configuration (inherit config)
                                           (rules (cons %backlight-udev-rule
                                                        (udev-configuration-rules config)))))))

(define garbage-collector-job
  #~(job '(next-hour) "guix gc --collect-garbage"))

(operating-system
  ;; (kernel linux)
  ;; (firmware (list linux-firmware))
  (locale "en_US.utf8")
  (timezone "America/New_York")
  (keyboard-layout (keyboard-layout "us"))
  (host-name "ben")
  (users (cons* (user-account
                 (name "ben")
                 (comment "Ben Ouattara")
                 (group "users")
                 (shell (file-append zsh "/bin/zsh"))
                 (home-directory "/home/ben")
                 (supplementary-groups
                  '("wheel" "netdev" "audio" "video" "lp")))
                (user-account
                 (name "danfodio")
                 (comment "Dan Fodio")
                 (group "users")
                 (shell (file-append zsh "/bin/zsh"))
                 (home-directory "/home/danfodio")
                 (supplementary-groups
                  '("wheel" "netdev" "audio" "video" "lp")))
                %base-user-accounts))
  (setuid-programs
   (append (list (setuid-program
                  (program (file-append stumpwm+slynk "/bin/stumpwm"))))
           %setuid-programs))
  (packages
   (append
    (list (list stumpwm "lib"))         ; use lib output of stumpwm package
    (list
     (specification->package "exfat-utils")
     (specification->package "xf86-input-libinput")
     (specification->package "sugar-light-sddm-theme")
     (specification->package "sugar-dark-sddm-theme")
     (specification->package "chili-sddm-theme")
     (specification->package "lightdm-gtk-greeter")
     (specification->package "font-tamzen")
     (specification->package "bluez")
     (specification->package "bluez-alsa")
     (specification->package "stumpwm-with-slynk")
     (specification->package "stow")
     (specification->package "pulseaudio")
     (specification->package "sbcl")
     (specification->package "awesome")
     (specification->package "i3-wm")
     (specification->package "i3status")
     ;; (specification->package "postgresql")
     (specification->package "dmenu")
     (specification->package "st")
     (specification->package "ratpoison")
     (specification->package "xterm")
     (specification->package "emacs-next")
     (specification->package "emacs-exwm")
     (specification->package
      "emacs-desktop-environment")
     (specification->package "nss-certs"))
    %base-packages))
  (services
   (append
    (list
     (service gnome-desktop-service-type)
     (simple-service 'system-cron-jobs
                     mcron-service-type
                     (list garbage-collector-job))
     (service postgresql-service-type)
     (service libvirt-service-type
              (libvirt-configuration
               (unix-sock-group "libvirt")
               (tls-port "16555")))
     (service console-font-service-type
              (map (lambda (tty)
                     (cons tty %beno-console-font))
                   '("tty1" "tty2" "tty3" "tty4" "tty5" "tty6")))
     (service thermald-service-type)
     (service darkstat-service-type
              (darkstat-configuration
               (interface "wlp0s20f3")))
     ;; (bluetooth-service #:auto-enable? #t)
     (service syncthing-service-type
              (syncthing-configuration (user "ben")))
     (service openssh-service-type
              ;; (openssh-configuration
              ;;  (x11-forwarding? #t)
              ;;  (permit-root-login 'prohibit-password)
              ;;  (password-authentication? #f)
              ;;  ;; (authorized-keys
              ;;  ;;  `(("ben" ,(local-file "ben.pub"))))
              ;;  )
              )
     (service tor-service-type)
     (service cups-service-type)
     (set-xorg-configuration
      (xorg-configuration
       (keyboard-layout keyboard-layout)
       (extra-config (list %xorg-libinput-config)))
      sddm-service-type)
     (service sddm-service-type
              (sddm-configuration
               ;; valid values are elarun, maldives or maya, chili, sugar-light, sugar-dark
               (theme "sugar-light")
               )))
    %modified-desktop-services))
  (name-service-switch %mdns-host-lookup-nss) ;; Allow resolution of '.local' host names with mDNS.
  (bootloader (bootloader-configuration
               (bootloader grub-bootloader)
               (targets (list "/dev/sda"))
               (keyboard-layout keyboard-layout)))
  (swap-devices (list (swap-space
                       (target (uuid
                                "e1da8300-e631-4435-a3f4-09d64a9bdbab")))))
  (file-systems (cons* (file-system
                        (mount-point "/boot/efi")
                        (device (uuid "27BA-B168"
                                      'fat32))
                        (type "vfat"))
                       (file-system
                        (mount-point "/")
                        (device (uuid
                                 "586e2f25-cb51-4d29-9282-bdca6b1ba29c"
                                 'ext4))
                        (type "ext4")) %base-file-systems))
  )
