(specifications->manifest
 (list
  "recutils"
  "emacs-guix"
  "xterm"
  "volumeicon"
  "pavucontrol"
  "arandr"
  "autorandr"
  "xrandr"
  "fd"
  "nyxt"
  "kitty"
  "alacritty"
  "picom"
  "feh"
  "xset"
  "setxkbmap"
  "xcape"
  "syncthing"
  "openssh"
  "git"
  "xfce4-screenshooter"
  "thunar"
  "lxappearance"
  "pcmanfm"
  "xbacklight"
  "brightnessctl"
  "neovim"

  ;; themes
  "arc-icon-theme"
  "matcha-theme"
  "hicolor-icon-theme"
  "gnome-icon-theme"
  "gnome-backgrounds"
  "papirus-icon-theme"
  "breeze-icons"

  ;; fonts
  "font-iosevka"
  "font-fira-code"
  "font-jetbrains-mono"
  ;; "font-iosevka-aile"
  "font-abattis-cantarell"
  "font-dejavu"
  "font-google-noto"
  "font-liberation"
  "font-awesome"
  "font-google-material-design-icons"

  ;; stump deps
  "sbcl-stumpwm-swm-gaps"
  "sbcl-stumpwm-ttf-fonts"
  "sbcl-stumpwm-stumptray"
  "sbcl-stumpwm-kbd-layouts"
  ;; "stumpwm-with-slynk"
  "sbcl-stumpwm-net"
  "sbcl-stumpwm-wifi"
  "stumpwm:lib"

  "syncthing"
  "xmodmap"

  "curl"
  "rlwrap"
  "ripgrep"
  "autoconf"
  "xsetroot"
  "nss-certs"
  "stumpish"
  "xdot"
  ;; "qutebrowser"
  "net-tools"
  "dstat"
  "clojure"
  "clojure-tools"
  "leiningen"
  "icedtea"
  ))
